[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-sdk = "3.2.0"
ckb-types = "0.116.1"
serde_json = "1.0.117"
secp256k1 = "0.24"
ckb-jsonrpc-types = "0.116.1"
ckb-hash = "0.116.1"
clap = { version = "4.5.4", features = ["derive"] }
hex-string = "0.1.0"