[workspace]
resolver = "2"

members = [
    "contracts/*",
    "tests",
    "plonk",
    "kzg",
    "verifier_client",
    "prover_client",
#    "test_plonk"
]

[profile.release]
overflow-checks = true
strip = true
codegen-units = 1
lto=true
Zlocation-detail="none"
opt-level="z"
