[workspace]
resolver = "2"

members = [
    "contracts/data_check",
    "contracts/plonk_verifier",
    "tests",
    "client",
    "plonk",
    "kzg"
]

[profile.release]
overflow-checks = true
strip = true
codegen-units = 1
